with open('app/mail.py', 'r', encoding='utf-8') as f:
    c = f.read()

new_func = '''def send_heartbeat_email(files_processed: int, files_failed: int, status: str, error_msg: str):
    """Sends a daily telemetry/health report to Canspirit developers."""
    try:
        dev_email = get_email_setting('developer_email', 'admin@canspirit.com')
        if not dev_email:
            return False
            
        subject = f"[{status.upper()}] Suprajit Portal Telemetry"
        
        body = f"Automated System Health Report\\n\\n"
        body += f"Sync Status: {status.upper()}\\n"
        body += f"Files Processed: {files_processed}\\n"
        body += f"Files Failed: {files_failed}\\n"
        
        if error_msg:
            body += f"\\nCRITICAL ERROR LOG:\\n{error_msg}\\n"
            
        body += "\\n\\n--\\nGenerated by Canspirit Suprajit Server."
        
        return _send_smtp(subject, [dev_email], body)
    except Exception as e:
        current_app.logger.error(f"Failed to send telemetry email: {e}")
        return False'''

c += "\\n" + new_func + "\\n"

with open('app/mail.py', 'w', encoding='utf-8') as f:
    f.write(c)
