[project]
name = "suprajit-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "4reeb-5yed", email = "4reeb-5yed@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "flask-limiter>=4.1.1",
    "flask-login>=0.6.3",
    "flask-mail>=0.10.0",
    "flask-wtf>=1.3.0",
    "python-dotenv>=1.2.3",
    "waitress>=3.0.2",
]

[project.scripts]
suprajit-v2 = "suprajit_v2:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]


