# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['web_server.py'],
    pathex=[],
    binaries=[],
    datas=[('app/templates', 'app/templates'), ('app/static', 'app/static')],
    hiddenimports=[
        'waitress',
        'flask',
        'openpyxl',
        'authlib',
        'app',
        'app.routes.auth',
        'app.routes.dashboard',
        'app.routes.search',
        'app.routes.api',
        'app.routes.export',
        'app.routes.admin',
        'app.routes.admin.dashboard',
        'app.routes.admin.users',
        'app.routes.admin.reports',
        'app.routes.admin.companies',
        'app.routes.admin.settings',
        'app.routes.admin.analytics',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['pytest', 'hypothesis', 'mutmut', 'playwright', 'anyio', 'coverage', 'setuptools', 'pip', 'wheel', 'tkinter', 'unittest'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SuprajitQualityPortal',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='SuprajitQualityPortal',
)
