import smtplib
from email.message import EmailMessage
from flask import current_app, request
from app.database import get_connection

def get_email_setting(key, default=""):
    try:
        conn = get_connection(current_app.config['DATABASE_PATH'])
        row = conn.execute("SELECT value FROM system_settings WHERE key = ?", (key,)).fetchone()
        conn.close()
        return row['value'] if row else default
    except Exception:
        return default

def _send_smtp(subject, recipients, body):
    smtp_server = get_email_setting('mail_server', 'smtp.gmail.com')
    smtp_port = int(get_email_setting('mail_port', '587'))
    smtp_user = get_email_setting('mail_username', '')
    smtp_pass = get_email_setting('mail_password', '')
    
    if not smtp_user or not smtp_pass:
        current_app.logger.error("Email credentials not configured in settings.")
        return False
        
    msg = EmailMessage()
    msg['Subject'] = subject
    msg['From'] = smtp_user
    msg['To'] = ", ".join(recipients)
    msg.set_content(body)
    
    try:
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        return True
    except Exception as e:
        current_app.logger.error(f"SMTP Error: {e}")
        return False

def get_serializer():
    from itsdangerous import URLSafeTimedSerializer
    return URLSafeTimedSerializer(current_app.config['SECRET_KEY'])

def send_password_reset_email(user_email: str, user_id: int):
    """Generates a token and sends a password reset email."""
    try:
        s = get_serializer()
        token = s.dumps(user_id, salt='password-reset-salt')
        reset_url = f"{request.host_url.rstrip('/')}/reset-password/{token}"
        
        body = f"Click the link to reset your password: {reset_url}\n\nThis link expires in 1 hour."
        return _send_smtp("Suprajit Quality Portal - Password Reset", [user_email], body)
    except Exception as e:
        current_app.logger.error(f"Failed to send reset email: {e}")
        return False

def send_welcome_email(user_email: str, username: str, raw_password: str, login_url: str = ""):
    """Sends a welcome email with initial login credentials."""
    try:
        if not login_url:
            try:
                login_url = f"{request.host_url.rstrip('/')}/login"
            except:
                login_url = "http://localhost:5000/login"
                
        body = f"Welcome to the Suprajit Quality Portal!\n\nAn administrator has created an account for you.\nYou can log in here: {login_url}\n\nYour Username: {username}\nYour Temporary Password: {raw_password}\n\nFor security reasons, please log in and change your password immediately or use the Forgot Password link."
        
        return _send_smtp("Welcome to Suprajit Quality Portal - Your Login Info", [user_email], body)
    except Exception as e:
        current_app.logger.error(f"Failed to send welcome email: {e}")
        return False
def send_heartbeat_email(files_processed: int, files_failed: int, status: str, error_msg: str):
    """Sends a daily telemetry/health report to Canspirit developers."""
    try:
        dev_email = get_email_setting('developer_email', '')
        if not dev_email:
            return False
            
        subject = f"[{status.upper()}] Suprajit Portal Telemetry"
        
        body = f"Automated System Health Report\n\n"
        body += f"Sync Status: {status.upper()}\n"
        body += f"Files Processed: {files_processed}\n"
        body += f"Files Failed: {files_failed}\n"
        
        if error_msg:
            body += f"\nCRITICAL ERROR LOG:\n{error_msg}\n"
            
        body += "\n\n--\nGenerated by Canspirit Suprajit Server."
        
        return _send_smtp(subject, [dev_email], body)
    except Exception as e:
        current_app.logger.error(f"Failed to send telemetry email: {e}")
        return False

